<a href="https://colab.research.google.com/github/cruzmarcela02/ciencia-de-datos/blob/main/TP1-aerolineas/colab-analisis/durabilidad_viajes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

pd.options.display.float_format = '{:20,.2f}'.format # suprimimos la notacion cientifica en los outputs

import warnings
warnings.filterwarnings('ignore')

In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

WARNING:root:pydrive is deprecated and no longer maintained. We recommend that you migrate your projects to pydrive2, the maintained fork of pydrive

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# **Cargamos archivos**

In [ ]:
# Cargamos archivos:
# 1. https://drive.google.com/file/d/1ZJIc1Y_0G4hdx_0GkTrw10IYrlAE4SoQ/view?usp=drive_link
id='1ZJIc1Y_0G4hdx_0GkTrw10IYrlAE4SoQ'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('filtered_customer_booking.csv')

In [ ]:
 # 2. https://drive.google.com/file/d/1XGEH-SRn9wde2vZC5lHtYjYNKSPtxsiY/view?usp=drive_link
id='1XGEH-SRn9wde2vZC5lHtYjYNKSPtxsiY'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('customer_airways_data.csv')

In [ ]:
# 3. https://drive.google.com/file/d/132CgYVqb-uygkp8wM80ur_cghtUDaEI7/view?usp=sharing
id='132CgYVqb-uygkp8wM80ur_cghtUDaEI7'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('cleaned-reviews.csv')

In [ ]:
# 4. https://drive.google.com/file/d/14GjEtEbD2al063LU0thzp-jRhuJKgvql/view?usp=drive_link
id='14GjEtEbD2al063LU0thzp-jRhuJKgvql'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('airline_data.csv')

# **Abrimos los DataFrame**

In [ ]:
archivo_uno = pd.read_csv('filtered_customer_booking.csv')
archivo_uno.shape # (n_filas, m_columnas)

(49982, 15)

In [ ]:
archivo_uno

,Unnamed: 0,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
0,0,2,Internet,RoundTrip,262,19,7,6,AKLDEL,New Zealand,1,0,0,5.52,0
1,1,1,Internet,RoundTrip,112,20,3,6,AKLDEL,New Zealand,0,0,0,5.52,0
2,2,2,Internet,RoundTrip,243,22,17,3,AKLDEL,India,1,1,0,5.52,0
3,3,1,Internet,RoundTrip,96,31,4,6,AKLDEL,New Zealand,0,0,1,5.52,0
4,4,2,Internet,RoundTrip,68,22,15,3,AKLDEL,India,1,0,1,5.52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49977,49995,2,Internet,RoundTrip,27,6,9,6,PERPNH,Australia,1,0,1,5.62,0
49978,49996,1,Internet,RoundTrip,111,6,4,7,PERPNH,Australia,0,0,0,5.62,0
49979,49997,1,Internet,RoundTrip,24,6,22,6,PERPNH,Australia,0,0,1,5.62,0
49980,49998,1,Internet,RoundTrip,15,6,11,1,PERPNH,Australia,1,0,1,5.62,0
49981,49999,1,Internet,RoundTrip,19,6,10,4,PERPNH,Australia,0,1,0,5.62,0

In [ ]:
archivo_uno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49982 entries, 0 to 49981
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             49982 non-null  int64
 1   num_passengers         49982 non-null  int64
 2   sales_channel          49982 non-null  object
 3   trip_type              49982 non-null  object
 4   purchase_lead          49982 non-null  int64
 5   length_of_stay         49982 non-null  int64
 6   flight_hour            49982 non-null  int64
 7   flight_day             49982 non-null  int64
 8   route                  49982 non-null  object
 9   booking_origin         49982 non-null  object
 10  wants_extra_baggage    49982 non-null  int64
 11  wants_preferred_seat   49982 non-null  int64
 12  wants_in_flight_meals  49982 non-null  int64
 13  flight_duration        49982 non-null  float64
 14  booking_complete       49982 non-null  int64
dtypes: float64(1), int64(10), object(4)
memory usage: 5.7+ MB

Analizamos los valores de las columnas:
*   wants_extra_baggage
*   wants_preferred_seat
*   wants_in_flight_meals
*   booking_complete

In [ ]:
archivo_uno['wants_extra_baggage'].unique()

array([1, 0])

In [ ]:
archivo_uno['wants_preferred_seat'].unique()

array([0, 1])

In [ ]:
archivo_uno['wants_in_flight_meals'].unique()

array([0, 1])

In [ ]:
archivo_uno['booking_complete'].unique()

array([0, 1])

# Tranformamos en tipo Booleano

**Definimos funcion para casos booleanos**

In [ ]:
def to_boolean(option):
  return option == 1

In [ ]:
archivo_uno['wants_extra_baggage'].map(to_boolean)
archivo_uno['wants_preferred_seat'].map(to_boolean)
archivo_uno['wants_in_flight_meals'].map(to_boolean)
archivo_uno['booking_complete'].map(to_boolean)
archivo_uno

,Unnamed: 0,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
0,0,2,Internet,RoundTrip,262,19,7,6,AKLDEL,New Zealand,1,0,0,5.52,0
1,1,1,Internet,RoundTrip,112,20,3,6,AKLDEL,New Zealand,0,0,0,5.52,0
2,2,2,Internet,RoundTrip,243,22,17,3,AKLDEL,India,1,1,0,5.52,0
3,3,1,Internet,RoundTrip,96,31,4,6,AKLDEL,New Zealand,0,0,1,5.52,0
4,4,2,Internet,RoundTrip,68,22,15,3,AKLDEL,India,1,0,1,5.52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49977,49995,2,Internet,RoundTrip,27,6,9,6,PERPNH,Australia,1,0,1,5.62,0
49978,49996,1,Internet,RoundTrip,111,6,4,7,PERPNH,Australia,0,0,0,5.62,0
49979,49997,1,Internet,RoundTrip,24,6,22,6,PERPNH,Australia,0,0,1,5.62,0
49980,49998,1,Internet,RoundTrip,15,6,11,1,PERPNH,Australia,1,0,1,5.62,0
49981,49999,1,Internet,RoundTrip,19,6,10,4,PERPNH,Australia,0,1,0,5.62,0

In [ ]:
archivo_uno['length_of_stay'].unique()

array([ 19,  20,  22,  31,  48,  33,  30,  25,  43,  24,  17,  34,  18,
        37,  29, 155,  88,  27,  21,  28,  47,  35,  82,  26,  90,  23,
        84,  61,  40,  96,  69,  89,  58,  56, 110, 165, 111,  38, 207,
        91,   1, 274,  44,  57, 106,  68,  87,  51, 196,  77,  41, 278,
       108, 180,  72,  32,  62,  45,  50,  59, 125, 124,  46,  55,  60,
        36,  65, 208, 204,  83,  42,  85,  64,  86,  54, 238, 275,  39,
        95,  70,  93,  49, 107, 121, 203, 188,  78, 209, 126,  80, 200,
       255,  63,  92, 118,  79, 181,  76,  94, 305, 149, 177, 183, 162,
        71, 109,  52, 140,  66, 184, 152,  53, 291, 329,  75, 130, 142,
       175,  73, 304, 186, 116, 101, 223, 415, 312, 143,  81, 144, 134,
       135, 117, 120, 138, 153,  74, 261, 103, 104, 112, 157, 266,  98,
       318,  67, 273, 105, 148, 102, 119, 122, 603, 465, 409, 128, 233,
        99, 113, 147, 127,  97, 170, 156, 160, 182, 115, 158,   0, 357,
       173, 228, 205, 178, 123, 352, 141, 139, 129, 301, 176, 332, 217,
       358, 285, 163, 359, 348, 392, 179, 132, 431, 236, 353, 137, 146,
       174, 224, 164, 306, 252, 171, 347, 185, 150, 361, 189, 343, 151,
       133, 230, 215, 256, 365, 168, 335, 349, 355, 331, 199, 254, 100,
       321, 245, 350, 326, 351, 356, 360, 262, 364, 229, 193, 194, 131,
       114, 191, 235, 239, 225, 190, 166, 280, 136, 330, 169, 345, 362,
       240, 145, 159, 267, 363, 192, 161, 322, 315, 289, 244, 327, 308,
       610, 172, 260, 778, 167, 226, 379, 334, 313, 342, 284, 237, 532,
       513, 201, 206, 221, 242, 369, 290, 297, 388, 282, 218, 286, 271,
       259, 510, 272, 292, 197, 277, 268, 435, 276, 220, 338, 303, 222,
       187, 247, 198, 195, 214, 337, 241, 311, 279, 316, 287, 478, 399,
       210, 341, 250, 202, 573, 216, 211, 773, 339, 294, 154, 517, 462,
       577, 231, 293, 213, 263,   2,   3,   4,   5,   6])

In [ ]:
archivo_uno.size # n_filas * m_columnas

749730

In [ ]:
len(archivo_uno) #cantidad de filas

49982

In [ ]:
archivo_uno.info() #tipo de dato por columna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49982 entries, 0 to 49981
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             49982 non-null  int64
 1   num_passengers         49982 non-null  int64
 2   sales_channel          49982 non-null  object
 3   trip_type              49982 non-null  object
 4   purchase_lead          49982 non-null  int64
 5   length_of_stay         49982 non-null  int64
 6   flight_hour            49982 non-null  int64
 7   flight_day             49982 non-null  int64
 8   route                  49982 non-null  object
 9   booking_origin         49982 non-null  object
 10  wants_extra_baggage    49982 non-null  int64
 11  wants_preferred_seat   49982 non-null  int64
 12  wants_in_flight_meals  49982 non-null  int64
 13  flight_duration        49982 non-null  float64
 14  booking_complete       49982 non-null  int64
dtypes: float64(1), int64(10), object(4)
memory usage: 5.7+ MB

In [ ]:
archivo_uno.memory_usage() #cantidad que la memoria usa

Index                       128
Unnamed: 0               399856
num_passengers           399856
sales_channel            399856
trip_type                399856
purchase_lead            399856
length_of_stay           399856
flight_hour              399856
flight_day               399856
route                    399856
booking_origin           399856
wants_extra_baggage      399856
wants_preferred_seat     399856
wants_in_flight_meals    399856
flight_duration          399856
booking_complete         399856
dtype: int64

In [ ]:
archivo_uno.count() # cuenta la cantidad de elementos por columna que tienen valor

Unnamed: 0               49982
num_passengers           49982
sales_channel            49982
trip_type                49982
purchase_lead            49982
length_of_stay           49982
flight_hour              49982
flight_day               49982
route                    49982
booking_origin           49982
wants_extra_baggage      49982
wants_preferred_seat     49982
wants_in_flight_meals    49982
flight_duration          49982
booking_complete         49982
dtype: int64

In [ ]:
archivo_uno.isnull().sum()

Unnamed: 0               0
num_passengers           0
sales_channel            0
trip_type                0
purchase_lead            0
length_of_stay           0
flight_hour              0
flight_day               0
route                    0
booking_origin           0
wants_extra_baggage      0
wants_preferred_seat     0
wants_in_flight_meals    0
flight_duration          0
booking_complete         0
dtype: int64

In [ ]:
archivo_uno.route.unique()

array(['AKLDEL', 'AKLHGH', 'AKLHND', 'AKLICN', 'AKLKIX', 'AKLKTM',
       'AKLKUL', 'AKLMRU', 'AKLPEK', 'AKLPVG', 'AKLTPE', 'AORICN',
       'AORKIX', 'AORKTM', 'AORMEL', 'BBIMEL', 'BBIOOL', 'BBIPER',
       'BBISYD', 'BDOCTS', 'BDOCTU', 'BDOHGH', 'BDOICN', 'BDOIKA',
       'BDOKIX', 'BDOMEL', 'BDOOOL', 'BDOPEK', 'BDOPER', 'BDOPUS',
       'BDOPVG', 'BDOSYD', 'BDOTPE', 'BDOXIY', 'BKICKG', 'BKICTS',
       'BKICTU', 'BKIHND', 'BKIICN', 'BKIKIX', 'BKIKTM', 'BKIMEL',
       'BKIMRU', 'BKIOOL', 'BKIPEK', 'BKIPER', 'BKIPUS', 'BKIPVG',
       'BKISYD', 'BKIXIY', 'BLRICN', 'BLRMEL', 'BLRPER', 'BLRSYD',
       'BOMMEL', 'BOMOOL', 'BOMPER', 'BOMSYD', 'BTJJED', 'BTUICN',
       'BTUPER', 'BTUSYD', 'BTUWUH', 'BWNCKG', 'BWNDEL', 'BWNHGH',
       'BWNIKA', 'BWNKTM', 'BWNMEL', 'BWNOOL', 'BWNPER', 'BWNSYD',
       'BWNTPE', 'CANDEL', 'CANIKA', 'CANMEL', 'CANMRU', 'CANOOL',
       'CANPER', 'CANSYD', 'CCUMEL', 'CCUMRU', 'CCUOOL', 'CCUPER',
       'CCUSYD', 'CCUTPE', 'CEBMEL', 'CEBOOL', 'CEBPER', 'CEBSYD',
       'CGKCKG', 'CGKCTS', 'CGKCTU', 'CGKDEL', 'CGKHGH', 'CGKHND',
       'CGKICN', 'CGKIKA', 'CGKJED', 'CGKKIX', 'CGKKTM', 'CGKMEL',
       'CGKMRU', 'CGKOOL', 'CGKPEK', 'CGKPER', 'CGKPUS', 'CGKPVG',
       'CGKSYD', 'CGKTPE', 'CGKWUH', 'CGKXIY', 'CKGCOK', 'CKGDPS',
       'CKGJHB', 'CKGKCH', 'CKGLOP', 'CKGMAA', 'CKGMEL', 'CKGMYY',
       'CKGOOL', 'CKGPEN', 'CKGPER', 'CKGPNH', 'CKGSBW', 'CKGSIN',
       'CKGSUB', 'CKGSYD', 'CKGTGG', 'CKGTRZ', 'CKGTWU', 'CMBCTS',
       'CMBCTU', 'CMBHGH', 'CMBHND', 'CMBICN', 'CMBKIX', 'CMBMEL',
       'CMBMRU', 'CMBOOL', 'CMBPEK', 'CMBPER', 'CMBPVG', 'CMBSYD',
       'CMBWUH', 'CNXHND', 'CNXICN', 'CNXKIX', 'CNXMEL', 'CNXOOL',
       'CNXPEK', 'CNXPER', 'CNXPVG', 'CNXSYD', 'CNXTPE', 'COKCTU',
       'COKHGH', 'COKICN', 'COKKIX', 'COKMEL', 'COKOOL', 'COKPER',
       'COKPUS', 'COKSYD', 'COKTPE', 'COKWUH', 'CRKMEL', 'CRKOOL',
       'CRKSYD', 'CSXPER', 'CTSDMK', 'CTSDPS', 'CTSHKT', 'CTSJHB',
       'CTSKBR', 'CTSKCH', 'CTSKNO', 'CTSLGK', 'CTSMEL', 'CTSMYY',
       'CTSOOL', 'CTSPEN', 'CTSPER', 'CTSSGN', 'CTSSIN', 'CTSSUB',
       'CTSSYD', 'CTUDPS', 'CTUHKT', 'CTUIKA', 'CTUJHB', 'CTUKBV',
       'CTUKCH', 'CTUKNO', 'CTUMAA', 'CTUMEL', 'CTUMRU', 'CTUMYY',
       'CTUOOL', 'CTUPEN', 'CTUPER', 'CTUSBW', 'CTUSIN', 'CTUSUB',
       'CTUSYD', 'CTUTGG', 'CTUTRZ', 'CTUTWU', 'CXRMEL', 'DACHGH',
       'DACHND', 'DACICN', 'DACKIX', 'DACMEL', 'DACOOL', 'DACPER',
       'DACSYD', 'DACTPE', 'DADMEL', 'DADOOL', 'DADSYD', 'DELDMK',
       'DELDPS', 'DELHKG', 'DELHKT', 'DELHND', 'DELJHB', 'DELJOG',
       'DELKBV', 'DELKCH', 'DELKIX', 'DELKNO', 'DELLGK', 'DELMEL',
       'DELMFM', 'DELMNL', 'DELMRU', 'DELMYY', 'DELOOL', 'DELPEN',
       'DELPER', 'DELPNH', 'DELSBW', 'DELSGN', 'DELSIN', 'DELSUB',
       'DELSYD', 'DELSZX', 'DMKHGH', 'DMKHND', 'DMKICN', 'DMKIKA',
       'DMKKIX', 'DMKKTM', 'DMKMEL', 'DMKMRU', 'DMKOOL', 'DMKPEK',
       'DMKPER', 'DMKPUS', 'DMKPVG', 'DMKSYD', 'DMKTPE', 'DPSHGH',
       'DPSHND', 'DPSICN', 'DPSIKA', 'DPSKIX', 'DPSKTM', 'DPSMEL',
       'DPSMRU', 'DPSOOL', 'DPSPEK', 'DPSPUS', 'DPSPVG', 'DPSSYD',
       'DPSTPE', 'DPSXIY', 'GOIKUL', 'GOIMEL', 'GOIOOL', 'GOIPER',
       'GOISYD', 'HANKTM', 'HANMEL', 'HANOOL', 'HANPER', 'HANSYD',
       'HDYHGH', 'HDYKTM', 'HDYMEL', 'HDYOOL', 'HDYPEK', 'HDYPER',
       'HDYPVG', 'HDYSYD', 'HDYTPE', 'HGHHKT', 'HGHJHB', 'HGHJOG',
       'HGHKBR', 'HGHKBV', 'HGHKCH', 'HGHKNO', 'HGHLGK', 'HGHLOP',
       'HGHMAA', 'HGHMEL', 'HGHMYY', 'HGHOOL', 'HGHPEN', 'HGHPER',
       'HGHSBW', 'HGHSUB', 'HGHSYD', 'HGHTRZ', 'HKGIKA', 'HKGKTM',
       'HKGMEL', 'HKGMRU', 'HKGOOL', 'HKGPER', 'HKGSYD', 'HKTHND',
       'HKTICN', 'HKTKIX', 'HKTKTM', 'HKTMEL', 'HKTMRU', 'HKTOOL',
       'HKTPEK', 'HKTPER', 'HKTPUS', 'HKTPVG', 'HKTSYD', 'HKTTPE',
       'HKTXIY', 'HNDIKA', 'HNDJOG', 'HNDKBR', 'HNDKBV', 'HNDKCH',
       'HNDKNO', 'HNDKTM', 'HNDLGK', 'HNDLOP', 'HNDMAA', 'HNDMEL',
       'HNDMLE', 'HNDOOL', 'HNDPEN', 'HNDPER', 'HNDPNH', 'HNDREP',
       'HNDRGN', 'HNDSBW', 'HNDSGN', 'HNDSIN', 'HNDSUB', 'HNDSYD',
       'HNDTRZ', 'HYDMEL', 'HYDOOL', 'HYDPER', 'HYDSYD', 'HYDWUH',
       'ICNIKA', 'ICNJED', 'ICNJHB', 'ICNKBR', 'ICNKBV', 'ICNKCH',
       'ICNKNO', 'ICNKTM', 'ICNLGK', 'ICNMAA', 'ICNMEL', 'ICNMLE',
       'ICNMYY', 'ICNOOL', 'ICNPEN', 'ICNPER', 'ICNREP', 'ICNRGN',
       'ICNSBW', 'ICNSDK', 'ICNSGN', 'ICNSIN', 'ICNSUB', 'ICNSYD',
       'ICNTRZ', 'ICNVTZ', 'IKAKCH', 'IKAKIX', 'IKALOP', 'IKAMEL',
       'IKAMFM', 'IKAMNL', 'IKAOOL', 'IKAPEK', 'IKAPEN', 'IKAPER',
       'IKAPUS', 'IKAPVG', 'IKASGN', 'IKASIN', 'IKASUB', 'IKASYD',
       'IKATPE', 'JEDJOG', 'JEDKNO', 'JEDMEL', 'JEDMNL', 'JEDPDG',
       'JEDPEN', 'JEDSUB', 'JHBKIX', 'JHBKTM', 'JHBMEL', 'JHBMRU',
       'JHBPEK', 'JHBPUS', 'JHBPVG', 'JHBSYD', 'JHBTPE', 'JHBWUH',
       'JHBXIY', 'JOGKIX', 'JOGKTM', 'JOGMEL', 'JOGOOL', 'JOGPER',
       'JOGPVG', 'JOGSYD', 'JOGTPE', 'KBRKIX', 'KBRKTM', 'KBRMEL',
       'KBROOL', 'KBRPEK', 'KBRPER', 'KBRPVG', 'KBRSYD', 'KBRTPE',
       'KBVKTM', 'KBVMEL', 'KBVOOL', 'KBVPEK', 'KBVPER', 'KBVPVG',
       'KBVSYD', 'KCHKIX', 'KCHKTM', 'KCHMEL', 'KCHMRU', 'KCHOOL',
       'KCHPEK', 'KCHPER', 'KCHPUS', 'KCHPVG', 'KCHSYD', 'KCHTPE',
       'KCHXIY', 'KHHMEL', 'KHHOOL', 'KHHPER', 'KHHSYD', 'KIXKNO',
       'KIXKTM', 'KIXLGK', 'KIXLOP', 'KIXMAA', 'KIXMEL', 'KIXMLE',
       'KIXMYY', 'KIXOOL', 'KIXPEN', 'KIXPER', 'KIXPNH', 'KIXREP',
       'KIXRGN', 'KIXSBW', 'KIXSGN', 'KIXSIN', 'KIXSUB', 'KIXSYD',
       'KIXTGG', 'KIXTRZ', 'KLOMEL', 'KLOOOL', 'KNOKTM', 'KNOMEL',
       'KNOOOL', 'KNOPEK', 'KNOPER', 'KNOPUS', 'KNOPVG', 'KNOSYD',
       'KNOTPE', 'KNOXIY', 'KOSMEL', 'KOSOOL', 'KOSPEK', 'KOSSYD',
       'KTMMEL', 'KTMMFM', 'KTMMYY', 'KTMPEN', 'KTMPER', 'KTMREP',
       'KTMSGN', 'KTMSIN', 'KTMSUB', 'KTMSYD', 'KTMTGG', 'KTMTPE',
       'KTMURT', 'KWLPER', 'LBUPER', 'LGKMEL', 'LGKOOL', 'LGKPER',
       'LGKPUS', 'LGKPVG', 'LGKSYD', 'LGKTPE', 'LOPOOL', 'LOPPEK',
       'LOPPVG', 'LOPSYD', 'LOPTPE', 'LOPXIY', 'LPQMEL', 'LPQOOL',
       'LPQPER', 'LPQTPE', 'MAAMEL', 'MAAMRU', 'MAAOOL', 'MAAPER',
       'MAAPVG', 'MAASYD', 'MAATPE', 'MAAWUH', 'MELMFM', 'MELMLE',
       'MELMNL', 'MELMRU', 'MELMYY', 'MELPEK', 'MELPEN', 'MELPNH',
       'MELPUS', 'MELPVG', 'MELREP', 'MELRGN', 'MELSBW', 'MELSGN',
       'MELSIN', 'MELSUB', 'MELSWA', 'MELSZX', 'MELTGG', 'MELTPE',
       'MELTRZ', 'MELTWU', 'MELURT', 'MELUTP', 'MELVTE', 'MELVTZ',
       'MELWUH', 'MELXIY', 'MFMOOL', 'MFMPER', 'MFMSYD', 'MLEPEK',
       'MLEPER', 'MLESYD', 'MNLMRU', 'MNLOOL', 'MNLPER', 'MNLSYD',
       'MRUOOL', 'MRUPEK', 'MRUPEN', 'MRUPER', 'MRUPVG', 'MRUSGN',
       'MRUSIN', 'MRUSUB', 'MRUSYD', 'MRUSZX', 'MYYOOL', 'MYYPER',
       'MYYPUS', 'MYYSYD', 'MYYXIY', 'NRTSYD', 'OOLPEK', 'OOLPEN',
       'OOLPNH', 'OOLPUS', 'OOLPVG', 'OOLREP', 'OOLRGN', 'OOLSBW',
       'OOLSDK', 'OOLSGN', 'OOLSIN', 'OOLSUB', 'OOLSZX', 'OOLTGG',
       'OOLTPE', 'OOLTRZ', 'OOLTWU', 'OOLURT', 'OOLUTP', 'OOLVTE',
       'OOLWUH', 'OOLXIY', 'PEKPEN', 'PEKPER', 'PEKREP', 'PEKRGN',
       'PEKSBW', 'PEKSIN', 'PEKSUB', 'PEKSYD', 'PEKTGG', 'PEKTRZ',
       'PEKTWU', 'PENPER', 'PENPUS', 'PENPVG', 'PENSYD', 'PENTPE',
       'PENWUH', 'PENXIY', 'PERPNH', 'PERPUS', 'PERPVG', 'PERREP',
       'PERRGN', 'PERSBW', 'PERSDK', 'PERSGN', 'PERSIN', 'PERSWA',
       'PERSZX', 'PERTGG', 'PERTPE', 'PERTRZ', 'PERTWU', 'PERUTP',
       'PERVTE', 'PERVTZ', 'PERWUH', 'PERXIY', 'PNHSYD', 'PNHTPE',
       'PNKTPE', 'PUSRGN', 'PUSSBW', 'PUSSGN', 'PUSSIN', 'PUSSUB',
       'PUSSYD', 'PUSTRZ', 'PVGREP', 'PVGRGN', 'PVGSIN', 'PVGSUB',
       'PVGSYD', 'PVGTGG', 'PVGTWU', 'PVGURT', 'REPSYD', 'REPTPE',
       'RGNSYD', 'RGNTPE', 'SBWSYD', 'SBWTPE', 'SBWXIY', 'SDKSYD',
       'SGNSYD', 'SGNXIY', 'SINSYD', 'SINTPE', 'SINWUH', 'SINXIY',
       'SRGTPE', 'SUBSYD', 'SUBTPE', 'SUBXIY', 'SYDSZX', 'SYDTPE',
       'SYDTRZ', 'SYDTWU', 'SYDVTE', 'SYDVTZ', 'SYDXIY', 'TGGTPE',
       'TGGXIY', 'TPETRZ', 'TPEVTE', 'TRZWUH', 'TRZXIY', 'TWUXIY',
       'HGHSGN', 'ICNTGG', 'JHBOOL', 'KBRXIY', 'KBVTPE', 'KIXTWU',
       'LBUTPE', 'PVGSGN', 'SBWWUH', 'DELREP', 'DPSWUH', 'HKGJED',
       'KBVKIX', 'KBVPUS', 'KIXLPQ', 'LGKPEK', 'LGKXIY', 'LOPPER',
       'PEKSGN', 'PERSUB', 'TPETWU', 'BDOWUH', 'BKIDEL', 'CKGSGN',
       'CTUKBR', 'CTULGK', 'CTUREP', 'DACMRU', 'DACPEK', 'DELRGN',
       'HDYXIY', 'HGHTGG', 'HKTWUH', 'ICNVTE', 'KBRPUS', 'KCHWUH',
       'KLOSYD', 'KNOWUH', 'MLETPE', 'SDKTPE', 'SUBWUH', 'TWUWUH',
       'AORPUS', 'BTUCKG', 'BWNWUH', 'CKGKNO', 'CKGLGK', 'CNXDEL',
       'CNXPUS', 'CTSJOG', 'CTSSBW', 'CTUDMK', 'CTULOP', 'DELKBR',
       'DELURT', 'HDYKIX', 'HGHSIN', 'HGHTWU', 'HYDMRU', 'IKASZX',
       'KBVWUH', 'KBVXIY', 'KIXLBU', 'LGKWUH', 'MELNRT', 'MLEOOL',
       'MRUTPE', 'TPEURT', 'URTXIY', 'AORPER', 'CKGHKT', 'CKGMRU',
       'CNXXIY', 'COKCTS', 'CSXMRU', 'CSXSYD', 'CTUMLE', 'CTUSGN',
       'CTUSRG', 'CTUURT', 'DACPUS', 'HGHMRU', 'HKTIKA', 'HKTJED',
       'ICNMRU', 'JEDMFM', 'KBRWUH', 'KIXMRU', 'KTMTWU', 'MLEPVG',
       'MRUXIY'], dtype=object)

In [ ]:
archivo_uno.route.value_counts() # para ver los mas polulares!

route
AKLKUL    2678
PENTPE     924
MELSGN     842
ICNSIN     801
DMKKIX     744
          ...
LBUTPE       1
CXRMEL       1
DELKBR       1
KOSSYD       1
MRUXIY       1
Name: count, Length: 799, dtype: int64

In [ ]:
archivo_dos = pd.read_csv("customer_airways_data.csv", encoding='iso-8859-1')
archivo_dos

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
0,2,Internet,RoundTrip,262,19,7,Sat,AKLDEL,New Zealand,1,0,0,5.52,0
1,1,Internet,RoundTrip,112,20,3,Sat,AKLDEL,New Zealand,0,0,0,5.52,0
2,2,Internet,RoundTrip,243,22,17,Wed,AKLDEL,India,1,1,0,5.52,0
3,1,Internet,RoundTrip,96,31,4,Sat,AKLDEL,New Zealand,0,0,1,5.52,0
4,2,Internet,RoundTrip,68,22,15,Wed,AKLDEL,India,1,0,1,5.52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2,Internet,RoundTrip,27,6,9,Sat,PERPNH,Australia,1,0,1,5.62,0
49996,1,Internet,RoundTrip,111,6,4,Sun,PERPNH,Australia,0,0,0,5.62,0
49997,1,Internet,RoundTrip,24,6,22,Sat,PERPNH,Australia,0,0,1,5.62,0
49998,1,Internet,RoundTrip,15,6,11,Mon,PERPNH,Australia,1,0,1,5.62,0
49999,1,Internet,RoundTrip,19,6,10,Thu,PERPNH,Australia,0,1,0,5.62,0

In [ ]:
archivo_tres = pd.read_csv('cleaned-reviews.csv')
archivo_tres

,Unnamed: 0,reviews,rates,date,country,verified,comments
0,0,✅ Trip Verified | Excellent service both on th...,5,2023-01-24,United Kingdom,True,excellent service ground board first class pro...
1,1,✅ Trip Verified | Good lounge at Cape Town. O...,9,2023-01-24,United Kingdom,True,good lounge cape town time departure drink hig...
2,2,✅ Trip Verified | A really excellent journey....,9,2023-01-23,United Kingdom,True,really excellent journey lounge overcrowded la...
3,3,✅ Trip Verified | This flight was one of the ...,9,2023-01-21,United Kingdom,True,flight one worst ever life wanted pamper bough...
4,4,Not Verified | It seems that there is a race t...,2,2023-01-19,United States,False,verified seems race bottom amongst airline can...
...,...,...,...,...,...,...,...
3406,3413,Flew British Airways from Sydney to Venice on ...,10,2014-05-20,Australia,False,flew british airway sydney venice nd april ret...
3407,3414,Recently for our honeymoon we took advantage o...,1,2014-05-19,United Kingdom,False,recently honeymoon took advantage ba promo fly...
3408,3415,LGW-Antigua on 29 April and Antigua-LGW on 13 ...,4,2014-05-18,United Kingdom,False,lgw antigua april antigua lgw may boeing start...
3409,3416,LHR-JTR-LHR. A tale of opposites for BA's new ...,2,2014-05-18,United Kingdom,False,lhr jtr lhr tale opposite ba new route santori...
3410,3417,Gatwick-Venice return. Two contrasting experie...,2,2014-05-18,United Kingdom,False,gatwick venice return two contrasting experien...

In [ ]:
archivo_cuatro = pd.read_csv('airline_data.csv')
archivo_cuatro

,Unnamed: 0,reviews,rates,date,country
0,0,✅ Trip Verified | Excellent service both on th...,5.00,24th January 2023,United Kingdom
1,1,✅ Trip Verified | Good lounge at Cape Town. O...,9.00,24th January 2023,United Kingdom
2,2,✅ Trip Verified | A really excellent journey....,9.00,23rd January 2023,United Kingdom
3,3,✅ Trip Verified | This flight was one of the ...,9.00,21st January 2023,United Kingdom
4,4,Not Verified | It seems that there is a race t...,2.00,19th January 2023,United States
...,...,...,...,...,...
3413,3413,Flew British Airways from Sydney to Venice on ...,6.00,20th May 2014,Australia
3414,3414,Recently for our honeymoon we took advantage o...,10.00,19th May 2014,United Kingdom
3415,3415,LGW-Antigua on 29 April and Antigua-LGW on 13 ...,1.00,18th May 2014,United Kingdom
3416,3416,LHR-JTR-LHR. A tale of opposites for BA's new ...,4.00,18th May 2014,United Kingdom
3417,3417,Gatwick-Venice return. Two contrasting experie...,2.00,18th May 2014,United Kingdom

**Entre los viajes realizados:**
*   ¿Cuáles tienen mas durabilidad?
*   ¿A caso los indivuales tienden a ser mas cortos que los grupales?

eliminar la primer columna
necesito filtrar los viajes validos
y separar en viajes de 1 o +1 funcion??
gruopby

In [ ]:
archivo_actualizado = archivo_uno.drop('Unnamed: 0', axis=1) # Borro la primer columna
archivo_actualizado

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
0,2,Internet,RoundTrip,262,19,7,6,AKLDEL,New Zealand,1,0,0,5.52,0
1,1,Internet,RoundTrip,112,20,3,6,AKLDEL,New Zealand,0,0,0,5.52,0
2,2,Internet,RoundTrip,243,22,17,3,AKLDEL,India,1,1,0,5.52,0
3,1,Internet,RoundTrip,96,31,4,6,AKLDEL,New Zealand,0,0,1,5.52,0
4,2,Internet,RoundTrip,68,22,15,3,AKLDEL,India,1,0,1,5.52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49977,2,Internet,RoundTrip,27,6,9,6,PERPNH,Australia,1,0,1,5.62,0
49978,1,Internet,RoundTrip,111,6,4,7,PERPNH,Australia,0,0,0,5.62,0
49979,1,Internet,RoundTrip,24,6,22,6,PERPNH,Australia,0,0,1,5.62,0
49980,1,Internet,RoundTrip,15,6,11,1,PERPNH,Australia,1,0,1,5.62,0
49981,1,Internet,RoundTrip,19,6,10,4,PERPNH,Australia,0,1,0,5.62,0

In [ ]:
pasajeros_estadias = archivo_actualizado[['num_passengers','length_of_stay']]
pasajeros_estadias

       num_passengers  length_of_stay
0                   2              19
1                   1              20
2                   2              22
3                   1              31
4                   2              22
...               ...             ...
49977               2               6
49978               1               6
49979               1               6
49980               1               6
49981               1               6

[49982 rows x 2 columns]

In [ ]:
pasajeros_estadias.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49982 entries, 0 to 49981
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   num_passengers  49982 non-null  int64
 1   length_of_stay  49982 non-null  int64
dtypes: int64(2)
memory usage: 781.1 KB

In [ ]:
pasajeros_estadias.describe()

            num_passengers       length_of_stay
count            49,982.00            49,982.00
mean                  1.59                23.05
std                   1.02                33.89
min                   1.00                 0.00
25%                   1.00                 5.00
50%                   1.00                17.00
75%                   2.00                28.00
max                   9.00               778.00

In [ ]:
# La cantidad de viajes con length_of_stay = 0 son pocos a la par de todo el dataframe
# Y como el booking_complete no esta completo, se decide descartar para el analisis
archivo_actualizado.loc[archivo_actualizado.length_of_stay == 0]

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
2195,1,Internet,OneWay,64,0,10,4,AKLTPE,Taiwan,1,0,0,4.67,0
3898,2,Internet,OneWay,24,0,0,1,CGKICN,Indonesia,1,0,1,6.62,0
3925,3,Internet,OneWay,44,0,7,7,CGKIKA,Iran,1,0,0,8.15,0
3999,1,Internet,OneWay,60,0,10,6,CGKKIX,Indonesia,0,1,0,7.00,0
4025,1,Internet,OneWay,84,0,5,3,CGKKIX,Indonesia,1,0,1,7.00,0
4491,1,Internet,OneWay,7,0,5,2,CKGKCH,Malaysia,1,1,0,4.83,0
10753,2,Internet,OneWay,46,0,20,1,DPSMEL,Chile,1,1,0,8.83,0
10918,2,Internet,RoundTrip,116,0,9,3,DPSPUS,South Korea,1,0,0,6.33,0
11077,1,Internet,OneWay,49,0,11,4,DPSSYD,Australia,0,0,1,8.58,0

In [ ]:
pasajeros_estadias = pasajeros_estadias.loc[pasajeros_estadias.length_of_stay != 0]
pasajeros_estadias

       num_passengers  length_of_stay
0                   2              19
1                   1              20
2                   2              22
3                   1              31
4                   2              22
...               ...             ...
49977               2               6
49978               1               6
49979               1               6
49980               1               6
49981               1               6

[49973 rows x 2 columns]

In [ ]:
cantidad = pasajeros_estadias.groupby(['num_passengers'])['length_of_stay'].count().to_frame().reset_index()
cantidad

   num_passengers  length_of_stay
0               1           31341
1               2           12792
2               3            2938
3               4            1783
4               5             561
5               6             289
6               7             114
7               8              89
8               9              66

In [ ]:
pasajeros_estadias['num_passengers'].value_counts()

num_passengers
1    31341
2    12792
3     2938
4     1783
5      561
6      289
7      114
8       89
9       66
Name: count, dtype: int64

In [ ]:
cantidad.pivot(values='cant', columns='length_of_stay', index='num_passengers')

KeyError: 'cant'

In [ ]:
pasajeros_estadias.groupby(['num_passengers']).agg({'length_of_stay':['max', 'min', 'count']}).reset_index()

  num_passengers length_of_stay
                            max min  count
0              1            778   1  31341
1              2            773   1  12792
2              3            335   1   2938
3              4            214   1   1783
4              5             72   1    561
5              6            362   2    289
6              7             72   1    114
7              8             78   2     89
8              9             30   3     66

In [ ]:
viajes_realizados = archivo_actualizado.loc[archivo_uno['booking_complete'] == 1]
viajes_realizados # Teniamos 49982, luego de filtrar 7476 elementos

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
82,1,Internet,RoundTrip,15,31,17,1,AKLKUL,Malaysia,0,0,0,8.83,1
86,1,Internet,RoundTrip,156,19,14,1,AKLKUL,Malaysia,1,0,0,8.83,1
94,1,Internet,RoundTrip,181,87,2,2,AKLKUL,Singapore,1,0,1,8.83,1
109,1,Mobile,RoundTrip,127,17,16,2,AKLKUL,Malaysia,1,0,1,8.83,1
122,1,Internet,RoundTrip,42,17,14,2,AKLKUL,Malaysia,0,0,0,8.83,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49954,1,Internet,RoundTrip,33,6,6,3,PENTPE,Taiwan,1,1,0,4.67,1
49959,2,Internet,RoundTrip,15,6,16,2,PENTPE,Malaysia,1,1,1,4.67,1
49962,4,Internet,RoundTrip,242,6,9,2,PENXIY,Malaysia,1,0,1,5.00,1
49966,2,Internet,RoundTrip,7,6,4,3,PERPNH,Australia,0,0,0,5.62,1
49969,3,Internet,RoundTrip,243,6,12,5,PERPNH,Australia,1,0,1,5.62,1

In [ ]:
# nros de a cuanto viaja la gente
viajes_realizados.num_passengers.unique()

array([1, 3, 4, 5, 2, 6, 8, 7, 9])

In [ ]:
individuales = viajes_realizados.loc[viajes_realizados['num_passengers'] == 1]
individuales

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
82,1,Internet,RoundTrip,15,31,17,1,AKLKUL,Malaysia,0,0,0,8.83,1
86,1,Internet,RoundTrip,156,19,14,1,AKLKUL,Malaysia,1,0,0,8.83,1
94,1,Internet,RoundTrip,181,87,2,2,AKLKUL,Singapore,1,0,1,8.83,1
109,1,Mobile,RoundTrip,127,17,16,2,AKLKUL,Malaysia,1,0,1,8.83,1
122,1,Internet,RoundTrip,42,17,14,2,AKLKUL,Malaysia,0,0,0,8.83,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49927,1,Internet,RoundTrip,75,6,13,5,PENTPE,Malaysia,0,0,0,4.67,1
49930,1,Internet,RoundTrip,90,6,16,1,PENTPE,Malaysia,1,0,0,4.67,1
49946,1,Internet,RoundTrip,42,6,10,7,PENTPE,Malaysia,1,1,1,4.67,1
49950,1,Internet,RoundTrip,25,6,12,5,PENTPE,Taiwan,0,0,0,4.67,1
49954,1,Internet,RoundTrip,33,6,6,3,PENTPE,Taiwan,1,1,0,4.67,1

In [ ]:
individuales.groupby('length_of_stay').count()

,num_passengers,sales_channel,trip_type,purchase_lead,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
length_of_stay,,,,,,,,,,,,,
1,38,38,38,38,38,38,38,38,38,38,38,38,38
2,117,117,117,117,117,117,117,117,117,117,117,117,117
3,337,337,337,337,337,337,337,337,337,337,337,337,337
4,571,571,571,571,571,571,571,571,571,571,571,571,571
5,668,668,668,668,668,668,668,668,668,668,668,668,668
...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,1,1,1,1,1,1,1,1,1,1,1,1,1
415,1,1,1,1,1,1,1,1,1,1,1,1,1
435,1,1,1,1,1,1,1,1,1,1,1,1,1
465,1,1,1,1,1,1,1,1,1,1,1,1,1
778,1,1,1,1,1,1,1,1,1,1,1,1,1

In [ ]:
grupales = viajes_realizados.loc[viajes_realizados['num_passengers'] != 1]
grupales

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
136,3,Internet,RoundTrip,229,17,13,1,AKLKUL,Malaysia,1,1,1,8.83,1
201,4,Internet,RoundTrip,316,22,14,4,AKLKUL,Malaysia,1,0,0,8.83,1
202,5,Internet,RoundTrip,67,35,2,2,AKLKUL,Malaysia,1,1,1,8.83,1
224,2,Internet,RoundTrip,245,27,11,1,AKLKUL,New Zealand,0,0,0,8.83,1
235,2,Internet,RoundTrip,235,18,22,2,AKLKUL,Malaysia,1,0,1,8.83,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49953,2,Mobile,RoundTrip,38,6,1,6,PENTPE,Malaysia,0,0,1,4.67,1
49959,2,Internet,RoundTrip,15,6,16,2,PENTPE,Malaysia,1,1,1,4.67,1
49962,4,Internet,RoundTrip,242,6,9,2,PENXIY,Malaysia,1,0,1,5.00,1
49966,2,Internet,RoundTrip,7,6,4,3,PERPNH,Australia,0,0,0,5.62,1
49969,3,Internet,RoundTrip,243,6,12,5,PERPNH,Australia,1,0,1,5.62,1

In [ ]:
duo = grupales.loc[grupales.num_passengers == 2]
duo.count()

num_passengers           2051
sales_channel            2051
trip_type                2051
purchase_lead            2051
length_of_stay           2051
flight_hour              2051
flight_day               2051
route                    2051
booking_origin           2051
wants_extra_baggage      2051
wants_preferred_seat     2051
wants_in_flight_meals    2051
flight_duration          2051
booking_complete         2051
dtype: int64

In [ ]:
a = grupales.groupby(['num_passengers'])['length_of_stay'].sum()
a

num_passengers
2    32032
3     5613
4     2607
5      932
6      396
7      116
8       73
9       89
Name: length_of_stay, dtype: int64

In [ ]:
grupales.num_passengers

136      3
201      4
202      5
224      2
235      2
        ..
49953    2
49959    2
49962    4
49966    2
49969    3
Name: num_passengers, Length: 3021, dtype: int64

In [ ]:
individuales.describe()

,num_passengers,purchase_lead,length_of_stay,flight_hour,flight_day,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
count,"4,455.00","4,455.00","4,455.00","4,455.00","4,455.00","4,455.00","4,455.00","4,455.00","4,455.00","4,455.00"
mean,1.00,61.69,23.52,9.08,3.75,0.70,0.33,0.44,6.90,1.00
std,0.00,74.44,37.58,5.25,1.95,0.46,0.47,0.50,1.58,0.00
min,1.00,0.00,1.00,0.00,1.00,0.00,0.00,0.00,4.67,1.00
25%,1.00,13.00,5.00,5.00,2.00,0.00,0.00,0.00,5.33,1.00
50%,1.00,35.00,6.00,9.00,4.00,1.00,0.00,0.00,7.00,1.00
75%,1.00,77.00,28.00,13.00,5.00,1.00,1.00,1.00,8.67,1.00
max,1.00,435.00,778.00,23.00,7.00,1.00,1.00,1.00,9.50,1.00

In [ ]:
individuales['length_of_stay'].value_counts()

length_of_stay
6      726
5      668
4      571
3      337
17     125
      ...
205      1
98       1
277      1
152      1
435      1
Name: count, Length: 163, dtype: int64

In [ ]:
viajes_realizados.flight_hour.unique()

array([17, 14,  2, 16, 13, 23,  9,  6, 11, 22,  4, 10, 12,  7,  3,  8, 15,
        5,  1,  0, 19, 21, 18, 20])

In [ ]:
viajes_realizados.flight_day.unique()

array([1, 2, 4, 7, 3, 6, 5])